services:
  db:
    image: postgis/postgis:16-3.4
    container_name: nexustransit_db
    environment:
      POSTGRES_DB: nexustransit
      POSTGRES_USER: nexustransit
      POSTGRES_PASSWORD: nexustransit
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: