# Generated by Django 6.0.5 on 2026-05-30 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=25)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('current_position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('heading', models.CharField(max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
